on: [pull_request]
name: Linter check

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - run: yarn install --frozen-lockfile --non-interactive

      - name: Run linter
        run: yarn run lint
